// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.

// tslint:disable

export declare const buildingName: string;
export declare const container: string;
export declare const image: string;
export declare const imageContainer: string;
export declare const infoContainer: string;
export declare const label: string;
export declare const link: string;
export declare const value: string;
