// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.

// tslint:disable

export declare const container: string;
export declare const map: string;
export declare const title: string;
