// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.

// tslint:disable

export declare const container: string;
export declare const header: string;
export declare const map: string;
export declare const searchButton: string;
export declare const searchContainer: string;
export declare const searchInput: string;
export declare const searchLabel: string;
export declare const title: string;
